# Generated by Django 4.2.1 on 2023-06-10 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='dep_decription',
            new_name='dep_description',
        ),
    ]
