# Generated by Django 4.2.1 on 2023-06-12 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_on',
            new_name='booked_on',
        ),
    ]
